version: '2'
services:

  bohiocontrols-frontend:
    build: frontend/.
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=BohioControls22
